//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class profile
    {
        [Required(ErrorMessage = "this field to continue")]
        public int ID { get; set; }
        [Required(ErrorMessage = "this field to continue")]
        public string Name { get; set; }
        [Required(ErrorMessage = "this field to continue")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required(ErrorMessage = "this field to continue")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        [Required(ErrorMessage = "this field to continue")]
        public string role { get; set; }
        [Required(ErrorMessage = "this field to continue")]
        public string address { get; set; }
        [Required(ErrorMessage = "this field to continue")]
        [DataType(DataType.Date)]

        public string birthdate { get; set; }

    }
}
